In [89]:
import pyforest 
from sqlalchemy import create_engine

In [90]:
price_engine = create_engine('sqlite:///../dataset/crypto_data.db')
df = pd.read_sql('BTC-USD',con=price_engine).tail(60).reset_index(drop=True)

In [91]:
pd.set_option('mode.chained_assignment', None)
df['extrem'] = 0
for i in range(5,len(df)):
    if df.iloc[i].High == df.iloc[i-5:i+5].High.max():
        df.extrem.iloc[i] = 1
    elif df.iloc[i].Low == df.iloc[i-5:i+5].Low.min():
        df.extrem.iloc[i] = -1
    else:
        continue

In [92]:
df

            Open          High           Low  ...       Volume   Datetime  extrem
0   22607.156250  22649.121094  21361.642578  ...  35574561406 2022-07-25       0
1   21361.121094  21361.121094  20776.816406  ...  28624673855 2022-07-26       0
2   21244.169922  22986.529297  21070.806641  ...  31758955233 2022-07-27       0
3   22933.640625  24110.470703  22722.265625  ...  40212386158 2022-07-28       0
4   23845.212891  24294.787109  23481.173828  ...  35887249746 2022-07-29       0
5   23796.818359  24572.580078  23580.507812  ...  28148218301 2022-07-30       1
6   23652.070312  24121.642578  23275.703125  ...  23553591896 2022-07-31       0
7   23336.718750  23464.787109  22890.796875  ...  25849159141 2022-08-01       0
8   23308.433594  23415.041016  22710.083984  ...  28389250717 2022-08-02       0
9   22981.302734  23578.650391  22747.835938  ...  26288169966 2022-08-03       0
10  22848.214844  23198.009766  22485.701172  ...  25120229769 2022-08-04      -1
11  22626.833984  23422.828125  22612.177734  ...  28881249043 2022-08-05       0
12  23291.423828  23326.562500  22961.279297  ...  15978259885 2022-08-06       0
13  22963.505859  23359.009766  22894.556641  ...  15886817043 2022-08-07       0
14  23179.527344  24203.689453  23176.546875  ...  28575544847 2022-08-08       0
15  23811.484375  23898.615234  22982.000000  ...  23555719219 2022-08-09       0
16  23162.898438  24127.414062  22771.519531  ...  32837431722 2022-08-10       0
17  23948.345703  24822.628906  23900.996094  ...  37127036580 2022-08-11       0
18  23957.203125  24412.566406  23657.265625  ...  27265804688 2022-08-12       0
19  24402.187500  24860.050781  24346.115234  ...  22987346289 2022-08-13       0
20  24429.056641  24974.914062  24206.259766  ...  22994133555 2022-08-14       0
21  24318.316406  25135.589844  23839.775391  ...  35123501685 2022-08-15       1
22  24126.136719  24228.416016  23733.500000  ...  27753685646 2022-08-16       0
23  23881.316406  24407.058594  23243.353516  ...  30931623076 2022-08-17       0
24  23341.039062  23563.832031  23177.601562  ...  23747613147 2022-08-18       0
25  23213.312500  23213.312500  20868.847656  ...  40509610260 2022-08-19       0
26  20872.841797  21350.806641  20856.730469  ...  27595671000 2022-08-20      -1
27  21160.392578  21668.845703  21103.197266  ...  23102307723 2022-08-21       0
28  21531.462891  21531.462891  20939.183594  ...  31666498758 2022-08-22       0
29  21401.044922  21646.203125  20955.138672  ...  31878280659 2022-08-23       0
30  21526.455078  21783.076172  21195.005859  ...  31962253368 2022-08-24       0
31  21395.458984  21789.636719  21362.441406  ...  31028679593 2022-08-25       0
32  21596.085938  21804.908203  20199.482422  ...  42326789564 2022-08-26       1
33  20262.480469  20340.775391  19890.523438  ...  30116729776 2022-08-27       0
34  20041.035156  20139.054688  19616.814453  ...  24366810591 2022-08-28       0
35  19615.154297  20357.462891  19600.785156  ...  32637854078 2022-08-29      -1
36  20298.611328  20542.644531  19617.640625  ...  34483360283 2022-08-30       0
37  19799.582031  20420.990234  19799.582031  ...  33225232872 2022-08-31       0
38  20050.498047  20198.390625  19653.968750  ...  30182031010 2022-09-01       0
39  20126.072266  20401.568359  19814.765625  ...  29123998928 2022-09-02       0
40  19969.718750  20037.009766  19698.355469  ...  23613051457 2022-09-03       0
41  19832.470703  19999.689453  19636.816406  ...  25245861652 2022-09-04       0
42  19988.789062  20031.160156  19673.046875  ...  28813460025 2022-09-05       0
43  19817.724609  20155.269531  18800.171875  ...  43403978910 2022-09-06       0
44  18837.683594  19427.171875  18644.466797  ...  35239757134 2022-09-07      -1
45  19289.941406  19417.351562  19076.714844  ...  32194477850 2022-09-08       0
46  19328.140625  21439.410156  19310.962891  ...  48469528171 2022-09-09       0
47  21376.912109  21760.275391  21168.722656  ...  36913738894 2022-09-10       0
48  21678.542969  21770.552734  21406.945312  ...  34493951963 2022-09-11       0
49  21770.148438  22439.181641  21603.896484  ...  50212088965 2022-09-12       0
50  22371.480469  22673.820312  20062.669922  ...  51091116622 2022-09-13       1
51  20184.554688  20467.201172  19793.396484  ...  37872380889 2022-09-14       0
52  20242.289062  20318.166016  19636.734375  ...  36389011503 2022-09-15       0
53  19704.005859  19870.628906  19400.076172  ...  30123362273 2022-09-16       0
54  19777.033203  20162.531250  19777.033203  ...  24957448100 2022-09-17       0
55  20127.234375  20127.234375  19387.492188  ...  31254779144 2022-09-18       0
56  19418.572266  19639.480469  18390.318359  ...  40177002624 2022-09-19       0
57  19545.591797  19602.457031  18813.455078  ...  36791346508 2022-09-20       0
58  18891.283203  19674.630859  18290.314453  ...  46363793975 2022-09-21      -1
59  18524.888672  18829.505859  18417.990234  ...  49544945664 2022-09-22       0

[60 rows x 8 columns]

In [110]:
max_val =  df[df.extrem == 1].High.max()
max_df = df[df.High == max_val]
max_index = max_df.index.values[0]
max_date = max_df.Datetime.values[0]
min_val = df.query('index > {}'.format(max_index)).Low.min()
min_index = df[df.Low == min_val].index.values[0]

min_date = df.query('Low == {}'.format(min_val))['Datetime'].values[0]
now_date = df.Datetime.tail(1).values[0]
# 
date_diff = int((min_date - max_date) / np.timedelta64(1, 'D'))
# decline rate
dec_rate = round((max_val - min_val) / max_val, 3)
date_diff, dec_rate, str(min_date)[:10]
# increase rate
now_price = df.tail(1).Close.values[0]
dis_bottom = round((now_price - min_val) / (max_val - min_val), 3)
# dis_top = round((max_val - now_price) / (max_val - min_val), 3)
dis_bottom, dec_rate

(0.064, 0.936, 0.272)

In [76]:
date_bottom = df.query('Low == {}'.format(min_val))
date_bottom = date_bottom['Datatime']
date_bottom

57   2022-09-19
Name: Datatime, dtype: datetime64[ns]

In [79]:
date_now = df.Datatime.tail(1)
date_now.values[0]

numpy.datetime64('2022-09-21T00:00:00.000000000')

In [80]:

date_diff

2.0

In [51]:
max_df = df[df.extrem == 1].tail(1)
max_value = max_df.High.values[0]

str(max_df.Datatime.values)[2:12]

'2022-09-13'

In [28]:
ind = df[df.extrem == 1].tail(1).High.index.values[0]
df.query('index > {} and extrem == -1'.format(ind)).Low.min()

18390.318359375

In [30]:
from datetime import datetime
date1 = datetime('2022-10-01')
d

TypeError: an integer is required (got type str)

In [31]:
int('2022-10-01'.split('-')[0])

2022

In [ ]:
d2 = datetime.datetime(2004, 12, 1)